apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-push-kaniko
  namespace: tekton-pipelines
spec:
  params:
  - name: IMAGE
    type: string
  workspaces:
  - name: source
  steps:
  - name: build
    image: gcr.io/kaniko-project/executor:latest
    env:
    - name: DOCKER_CONFIG
      value: /tekton/home/.docker
    args:
    - --destination=$(params.IMAGE)
    - --context=$(workspaces.source.path)
    - --dockerfile=$(workspaces.source.path)/Dockerfile